// Run with an installed Playwright package; PLAYWRIGHT_MODULE may name its absolute path.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch();try{const page=await browser.newPage();
await page.clock.install();
const config={domain:'localhost',mode:'local',scheme:'http',tailscale:'test.ts.net',connected:'gateway',ports:{gateway:'8446',litellm:'8443',langfuse:'8444',s3:'8445',observability:'8447',backplane:'8448'}};
const html=()=>fs.readFileSync('docker/console/index.html','utf8').replace(/(<script type="application\/json" id="edge-config">)[\s\S]*?(<\/script>)/,'$1'+JSON.stringify(config)+'$2');
await page.route('https://test.ts.net/**',r=>{const p=new URL(r.request().url()).pathname;return r.fulfill({status:200,contentType:p==='/edge-config.json'?'application/json':p.startsWith('/health/')?'text/plain':'text/html',body:p==='/edge-config.json'?JSON.stringify(config):p.startsWith('/health/')?'':html()});});
await page.goto('https://test.ts.net/');await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
const link=page.locator('a.open').filter({hasText:'Open Agent Backplane'});assert.equal(await link.getAttribute('href'),null);
config.connected+=',backplane';await page.getByRole('button',{name:'Check again',exact:true}).click();await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
assert.equal(await link.getAttribute('href'),'https://test.ts.net:8448/dashboard','Check again must discover newly configured Backplane without page reload');
config.connected='gateway';await page.clock.fastForward(30000);
await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
assert.equal(await link.getAttribute('href'),null,'Automatic refresh must remove disconnected links');
config.connected+=',backplane';await page.clock.fastForward(30000);
await page.waitForFunction(()=>!document.querySelector('#refresh').disabled);
assert.equal(await link.getAttribute('href'),'https://test.ts.net:8448/dashboard','Automatic refresh must add newly connected links');
console.log('PASS: manual refresh discovers new app; automatic refresh removes and restores its link');
}finally{await browser.close();}})().catch(e=>{console.error(e.message);process.exitCode=1});
