// Stack architecture, not a runtime inventory. Component health requires public status evidence.
const DATA = {
  projects: [
    {
      id: "gateway",
      name: "LLM Gateway",
      description: "Models, tracing and usage.",
      icon: "gateway",
      primary: "lite",
      repo: "llm-gateway-stack",
    },
    {
      id: "backplane",
      name: "Agent Backplane",
      description: "Shared state and work for your agents.",
      icon: "backplane",
      primary: "bp",
      repo: "agent-backplane",
    },
    {
      id: "observability",
      name: "Observability",
      description: "Logs, metrics and traces in one place.",
      icon: "observability",
      primary: "grafana",
      repo: "observability-stack",
    },
    {
      id: "edge",
      name: "Platform Edge",
      description: "Private access to your applications.",
      icon: "edge",
      primary: "edge",
      repo: "platform-edge",
    },
  ],
  services: [
    {
      id: "lite",
      project: "gateway",
      name: "LiteLLM",
      description: "Choose models, manage API keys and set budgets.",
      kind: "app",
      icon: "litellm",
      links: {},
      uses: ["g-pg", "valkey", "langfuse"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "langfuse",
      project: "gateway",
      name: "Langfuse",
      description: "Explore traces, prompts and evaluations.",
      kind: "app",
      icon: "langfuse",
      links: {},
      uses: ["g-pg", "clickhouse", "valkey", "g-rust"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "g-rust",
      project: "gateway",
      name: "RustFS",
      description: "Stores Langfuse events, uploads and exports.",
      kind: "backend",
      icon: "rustfs",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "g-pg",
      project: "gateway",
      name: "PostgreSQL",
      description: "Stores model settings, accounts and project metadata.",
      kind: "backend",
      icon: "postgres",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "clickhouse",
      project: "gateway",
      name: "ClickHouse",
      description: "Stores trace and analytics data.",
      kind: "backend",
      icon: "clickhouse",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "valkey",
      project: "gateway",
      name: "Valkey",
      description: "Caches responses and queues background work.",
      kind: "backend",
      icon: "valkey",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "lf-worker",
      project: "gateway",
      name: "Langfuse worker",
      description: "Processes queued events and exports.",
      kind: "worker",
      icon: "langfuse",
      links: {},
      uses: ["g-pg", "clickhouse", "valkey", "g-rust"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "g-caddy",
      project: "gateway",
      name: "Caddy",
      description: "Routes requests to Gateway applications.",
      kind: "infra",
      icon: "caddy",
      links: {},
      uses: ["lite", "langfuse", "g-rust"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "pg-export",
      project: "gateway",
      name: "Postgres exporter",
      description: "Publishes database metrics for Alloy.",
      kind: "worker",
      icon: "prometheus",
      links: {},
      uses: ["g-pg"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "vk-export",
      project: "gateway",
      name: "Valkey exporter",
      description: "Publishes queue and cache metrics for Alloy.",
      kind: "worker",
      icon: "prometheus",
      links: {},
      uses: ["valkey"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "g-init",
      project: "gateway",
      name: "Prepare object storage",
      description: "Creates storage buckets and configures application access.",
      kind: "setup",
      icon: "setup",
      links: {},
      uses: ["g-rust"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "bp",
      project: "backplane",
      name: "Backplane",
      description: "Manage workspaces, agent access and approvals.",
      kind: "app",
      icon: "backplane",
      links: {},
      uses: ["b-pg", "files"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "b-pg",
      project: "backplane",
      name: "PostgreSQL",
      description: "Stores workspace data, queues and audit history.",
      kind: "backend",
      icon: "postgres",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "files",
      project: "backplane",
      name: "Files",
      description: "Provides file access through the selected storage backend.",
      kind: "capability",
      icon: "files",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "workerd",
      project: "backplane",
      name: "workerd",
      description: "Runs agent functions in isolated workers.",
      kind: "worker",
      icon: "workerd",
      links: {},
      uses: [],
      optional: true,
      version: null,
      state: "unknown",
    },
    {
      id: "b-rust",
      project: "backplane",
      name: "RustFS",
      description: "Optional object storage for agent files.",
      kind: "backend",
      icon: "rustfs",
      links: {},
      uses: [],
      optional: true,
      version: null,
      state: "unknown",
    },
    {
      id: "b-caddy",
      project: "backplane",
      name: "Caddy",
      description: "Routes browser requests to Backplane.",
      kind: "infra",
      icon: "caddy",
      links: {},
      uses: ["bp"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "b-init",
      project: "backplane",
      name: "Prepare object storage",
      description: "Creates storage buckets and configures application access.",
      kind: "setup",
      icon: "setup",
      links: {},
      uses: ["b-rust"],
      optional: true,
      version: null,
      state: "unknown",
    },
    {
      id: "grafana",
      project: "observability",
      name: "Grafana",
      description: "Explore dashboards, logs, metrics and traces.",
      kind: "app",
      icon: "grafana",
      links: {},
      uses: ["loki", "mimir", "tempo"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "loki",
      project: "observability",
      name: "Loki",
      description: "Stores and searches logs.",
      kind: "backend",
      icon: "loki",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "mimir",
      project: "observability",
      name: "Mimir",
      description: "Stores and queries metrics.",
      kind: "backend",
      icon: "mimir",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "tempo",
      project: "observability",
      name: "Tempo",
      description: "Stores and searches distributed traces.",
      kind: "backend",
      icon: "tempo",
      links: {},
      uses: [],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "alloy",
      project: "observability",
      name: "Alloy",
      description: "Collects telemetry and sends it to the right store.",
      kind: "worker",
      icon: "alloy",
      links: {},
      uses: ["loki", "mimir", "tempo"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "o-caddy",
      project: "observability",
      name: "Caddy",
      description: "Routes browser requests to Grafana.",
      kind: "infra",
      icon: "caddy",
      links: {},
      uses: ["grafana"],
      optional: false,
      version: null,
      state: "unknown",
    },
    {
      id: "o-rust",
      project: "observability",
      name: "RustFS",
      description: "Optional object storage for logs, metrics and traces.",
      kind: "backend",
      icon: "rustfs",
      links: {},
      uses: [],
      optional: true,
      version: null,
      state: "unknown",
    },
    {
      id: "o-init",
      project: "observability",
      name: "Prepare object storage",
      description: "Creates storage buckets and configures application access.",
      kind: "setup",
      icon: "setup",
      links: {},
      uses: ["o-rust"],
      optional: true,
      version: null,
      state: "unknown",
    },
    {
      id: "edge",
      project: "edge",
      name: "Caddy",
      description: "Connects the three projects through one ingress.",
      kind: "infra",
      icon: "caddy",
      links: {},
      uses: ["g-caddy", "b-caddy", "o-caddy"],
      optional: false,
      version: null,
      state: "unknown",
    },
  ],
  icons: {
    litellm: "/console/icons/litellm.png",
    langfuse: "/console/icons/langfuse.svg",
    rustfs: "/console/icons/rustfs.svg",
    grafana: "/console/icons/grafana.svg",
    gateway: "/console/icons/gateway.svg",
    backplane: "/console/icons/backplane.svg",
    edge: "/console/icons/edge.svg",
    observability: "/console/icons/observability.svg",
    setup: "/console/icons/setup.svg",
    files: "/console/icons/files.svg",
    caddy: "/console/icons/caddy.svg",
    workerd: "/console/icons/workerd.svg",
    prometheus: "/console/icons/prometheus.svg",
    clickhouse: "/console/icons/clickhouse.svg",
    mimir: "/console/icons/mimir.svg",
    loki: "/console/icons/loki.svg",
    valkey: "/console/icons/valkey.svg",
    alloy: "/console/icons/alloy.svg",
    postgres: "/console/icons/postgres.svg",
    tempo: "/console/icons/tempo.svg",
    github: "/console/icons/github.svg",
  },
};

// Contract tasks and capabilities share the existing supporting-service layout.
for (const [project, statusId, name, kind] of [
  ["edge", "bootstrap", "Prepare installation", "setup"],
  ["gateway", "bootstrap", "Prepare installation", "setup"],
  ["observability", "bootstrap", "Prepare installation", "setup"],
  ["backplane", "bootstrap", "Prepare installation", "setup"],
  ["backplane", "migrate", "Apply database migrations", "setup"],
  ["backplane", "data-init", "Prepare file permissions", "setup"],
  ["backplane", "functions", "Functions", "capability"],
])
  DATA.services.push({
    id: `${project}-${statusId}`,
    statusId,
    project,
    name,
    kind,
    description:
      kind === "setup"
        ? "Latest recorded execution; not continuous readiness."
        : "Configured function deployment and invocation capability.",
    icon: kind === "setup" ? "setup" : "workerd",
    links: {},
    uses: [],
    optional: false,
  });
